const LOG_IN = "LOGIN";
const LOG_OUT = "LOGOUT";
const HIDE_LOGIN_ALERT = "HIDE_LOGIN_ALERT";
// const ADD_TRANSACTION = ""\\
const SUBSCRIBE_FOR_TXNS = "SUBSCRIBE_FOR_TXNS";
const UPDATE_DATA = "UPDATE_DATA";
const UNSUBSCRIBE_FOR_TXNS = "UNSUBSCRIBE_FOR_TXNS";

export {
  LOG_IN,
  LOG_OUT,
  HIDE_LOGIN_ALERT,
  SUBSCRIBE_FOR_TXNS,
  UNSUBSCRIBE_FOR_TXNS,
  UPDATE_DATA,
};
